### ISSUE TITLE
`set_` functions with no args cause error

### ISSUE THREAD

**Issue by austin1howard** [austin1howard/mpxl#1]
If a function only has kwargs, it causes an error when including. Removing the `*args` from the call in `_runkaplotfunction` fixes, so probably need to find call signature.

**Comment by kamilm** [comment]
What does that mean? 

mobile email
Kamil Mielczarek

**Comment by austin1howard** [comment]
It means I found a bug. I put it in the bug tracker so I would remember what to fix. If I fix it "right" it might be a little tricky.

Sent from my iPhone

On May 10, 2014, at 10:12 AM, "Kamil Mielczarek" <notifications@github.com<mailto:notifications@github.com>> wrote:

What does that mean?

mobile email
Kamil Mielczarek
